services:
  - type: web
    name: backend
    env: python
    repo: https://github.com/MeritonD/language_learning_llm.git
    branch: master
    rootDir: backend
    buildFilter:
      paths:
      - backend/**
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6

  - type: web
    name: frontend
    env: node
    repo: https://github.com/MeritonD/language_learning_llm.git
    branch: master
    rootDir: frontend
    buildFilter:
      paths:
      - frontend/**
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s build"
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
